name: Build Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Install Grype
        id: install-grype
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
      - name: Login to Docker Hub
        id: docker-login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker image
        id: build-docker-image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/prometheus-go-app:$(git rev-parse --short "$GITHUB_SHA")