apiVersion: v1
kind: Service
metadata:
  name: go-application
  namespace: monitoring
  labels:
    app: go-application
spec:
  selector:
    app: go-application
  ports:
    - port: 2112
      targetPort: 2112
      name: web
