name: apply environment manifests
on:
  push:
    branches:
      - main
jobs:
  apply-environment-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install terraform
        id: install-terraform
        run: wget -O terraform.zip https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && sudo mv terraform /usr/local/bin
      - name: Install KinD
        id: install-kind
        run: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 && chmod +x ./kind && sudo mv ./kind /usr/local/bin/kind
      - name: Apply Terraform
        id: apply-terraform
        working-directory: ./Environments/Terraform
        run: terraform init && terraform apply -auto-approve -var="branch=${GITHUB_REF##*/}"